########################### DATA ###########################
image_style: "processed"
image_size: [100, 200]
shuffle: True

#test data's authors
test_0: "Bajza_Jozsef"
test_1: "Bajza_Jozsef"
test_2: "Bajza_Jozsef"
test_3: "Bajza_Jozsef"
test_4: "Bajza_Jozsef"
test_5: "Bajza_Jozsef"
test_6: "Bajza_Jozsef"
test_7: "Bajza_Jozsef"
test_8: "Bajza_Jozsef"
test_9: "Bajza_Jozsef"
test_10: "Bajza_Jozsef"
test_11: "Bajza_Jozsef"
test_12: "Bajza_Jozsef"
test_13: "Bajza_Jozsef"
test_14: "Guzmics_Izidor"
test_15: "Guzmics_Izidor"
test_16: "Guzmics_Izidor"
test_17: "Guzmics_Izidor"
test_18: "Guzmics_Izidor"
test_19: "Guzmics_Izidor"
test_20: "Guzmics_Izidor"
test_21: "Guzmics_Izidor"
test_22: "Guzmics_Izidor"
test_23: "Guzmics_Izidor"
test_24: "Helmeczy_Mihaly"
test_25: "Helmeczy_Mihaly"
test_26: "Helmeczy_Mihaly"
test_27: "Helmeczy_Mihaly"
test_28: "Helmeczy_Mihaly"
test_29: "Kazinczy_Ferenc"
test_30: "Kazinczy_Ferenc"
test_31: "Kazinczy_Ferenc"
test_32: "Kazinczy_Ferenc"
test_33: "Kazinczy_Ferenc"
test_34: "Kazinczy_Ferenc"
test_35: "Kazinczy_Gabor"
test_36: "Kazinczy_Gabor"
test_37: "Kazinczy_Gabor"
test_38: "Kazinczy_Gabor"
test_39: "Kazinczy_Gabor"
test_40: "Kazinczy_Gabor"
test_41: "Kazinczy_Gabor"
test_42: "Kazinczy_Gabor"
test_43: "Kazinczy_Gabor"
test_44: "Kazinczy_Gabor"
test_45: "Kazinczy_Gabor"
test_46: "Kazinczy_Gabor"
test_47: "Kazinczy_Gabor"
test_48: "Kazinczy_Gabor"
test_49: "Kazinczy_Gabor"
test_50: "Kazinczy_Gabor"
test_51: "Kazinczy_Gabor"
test_52: "Kazinczy_Gabor"
test_53: "Kazinczy_Gabor"
test_54: "Kazinczy_Gabor"
test_55: "Kazinczy_Gabor"
test_56: "Kazinczy_Gabor"
test_57: "Kazinczy_Gabor"
test_58: "Kazinczy_Gabor"
test_59: "Kazinczy_Gabor"
test_60: "Kazinczy_Gabor"
test_61: "Kazinczy_Gabor"
test_62: "Kazinczy_Gabor"
test_63: "Kazinczy_Gabor"
test_64: "Kazinczy_Gabor"
test_65: "Kazinczy_Gabor"
test_66: "Kazinczy_Gabor"
test_67: "Kazinczy_Gabor"
test_68: "Kazinczy_Gabor"
test_69: "Kazinczy_Gabor"
test_70: "Kazinczy_Gabor"
test_71: "Kazinczy_Gabor"
test_72: "Kazinczy_Gabor"
test_73: "Kazinczy_Gabor"
test_74: "Kazinczy_Gabor"
test_75: "Kazinczy_Gabor"
test_76: "Kazinczy_Gabor"
test_77: "Kazinczy_Gabor"
test_78: "Kazinczy_Gabor"
test_79: "Kazinczy_Gabor"
test_80: "Kazinczy_Gabor"
test_81: "Kazinczy_Gabor"
test_82: "Kazinczy_Gabor"
test_83: "Kazinczy_Gabor"
test_84: "Kolcsey Ferenc"
test_85: "Kolcsey Ferenc"
test_86: "Kolcsey Ferenc"
test_87: "Kolcsey Ferenc"
test_88: "Kolcsey Ferenc"
test_89: "Kolcsey Ferenc"
test_90: "Kolcsey Ferenc"
test_91: "Kolcsey Ferenc"
test_92: "Stettner Gyorgy"
test_93: "Stettner Gyorgy"
test_94: "Stettner Gyorgy"
test_95: "Stettner Gyorgy"
test_96: "Stettner Gyorgy"
test_97: "Stettner Gyorgy"
test_98: "Stettner Gyorgy"
test_99: "Stettner Gyorgy"
test_100: "Stettner Gyorgy"
test_101: "Toldy_Ferenc"
test_102: "Toldy_Ferenc"

################ OPTIONAL FEATURE EXTRACTORS ###############
#   - "resnet50_pretrained"
#   - "sift"
#   - "our_cnn_trained"
feature_extractor: "our_cnn_trained"

#paths for the trained extractors
our_trained_model_path: "trained_models/feature_extractors/our_cnn_trained.h5"

##################### OPTIONAL CLASSIFIERS #################
#   - "mlp"
#   - "linear_svm"
#   - "rbf_svm"
#   - "decision_tree"
#   - "random_forest"
#   - "naive_bayes"
#   - "qda"
#   - "k_nn"
classifier: "k_nn"


#paths for the trained classifiers
mlp_trained_path: "trained_models/classifiers/mlp_trained.h5"
linear_svm_trained_path: "trained_models/classifiers/linear_svm_trained.sav"
rbf_svm_trained_path: "trained_models/classifiers/rbf_svm_trained.sav"
decision_tree_trained_path: "trained_models/classifiers/decision_tree_trained.sav"
random_forest_trained_path: "trained_models/classifiers/random_forest_trained.sav"
naive_bayes_trained_path: "trained_models/classifiers/naive_bayes_trained.sav"
qda_trained_path: "trained_models/classifiers/qda_trained.sav"
k_nn_trained_path: "trained_models/classifiers/k_nn_trained.joblib"

batch_size: 32 # EZ NEM KELL MAJD IDE!!!
