########################### DATA ###########################
input_folder: "dataset/ready_for_train/cropped_processed"
# splits
train_split: 0.8
validation_split: 0.2
#train_split is from other folder, only for test purposes
image_size: [100, 200]
batch_size: 1024


################ OPTIONAL FEATURE EXTRACTORS ###############
#   - "resnet50_pretrained"
#   - "sift"
#   - "our_cnn_trained"
feature_extractor: "our_cnn_trained"

#paths for the extractors
our_trained_model_path: "trained_models/feature_extractors/our_cnn_trained.h5"

##################### OPTIONAL CLASSIFIERS #################
#   - "mlp"
#   - "linear_svm"
#   - "rbf_svm"
#   - "decision_tree"
#   - "random_forest"
#   - "naive_bayes"
#   - "qda"
#   - "k_nn"
classifier: "decision_tree"


################### classifier configs ###################

# for MLP
learning_rate: 0.0001
nr_of_epochs: 30


# for linear svm

# for rbf svm

# decision tree


# for k-nn
k: 3


